// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/goimagesearch.proto

/*
Package goimagesearch is a generated protocol buffer package.

It is generated from these files:
	proto/goimagesearch.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package goimagesearch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GoImageSearch service

type GoImageSearchService interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error)
}

type goImageSearchService struct {
	c    client.Client
	name string
}

func NewGoImageSearchService(name string, c client.Client) GoImageSearchService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "goimagesearch"
	}
	return &goImageSearchService{
		c:    c,
		name: name,
	}
}

func (c *goImageSearchService) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error) {
	req := c.c.NewRequest(c.name, "GoImageSearch.Ping", in)
	out := new(PingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoImageSearch service

type GoImageSearchHandler interface {
	Ping(context.Context, *PingRequest, *PingResponse) error
}

func RegisterGoImageSearchHandler(s server.Server, hdlr GoImageSearchHandler, opts ...server.HandlerOption) {
	type goImageSearch interface {
		Ping(ctx context.Context, in *PingRequest, out *PingResponse) error
	}
	type GoImageSearch struct {
		goImageSearch
	}
	h := &goImageSearchHandler{hdlr}
	s.Handle(s.NewHandler(&GoImageSearch{h}, opts...))
}

type goImageSearchHandler struct {
	GoImageSearchHandler
}

func (h *goImageSearchHandler) Ping(ctx context.Context, in *PingRequest, out *PingResponse) error {
	return h.GoImageSearchHandler.Ping(ctx, in, out)
}
